In [1]:
import os
import numpy as np
import pandas as pd
import healpy as hp
from astropy.time import Time, TimeDelta
from astropy.coordinates import SkyCoord
from astroplan import Observer
import astropy.units as u

from rubin_nights import connections
from rubin_nights import lfa_data
from rubin_nights import plot_utils as rn_plots

from IPython.display import display, HTML
import matplotlib.pyplot as plt

import pickle
from lsst.resources import ResourcePath
from rubin_scheduler.scheduler.schedulers import CoreScheduler
from rubin_scheduler.scheduler.features import Conditions
from rubin_scheduler.scheduler.model_observatory import ModelObservatory
from rubin_scheduler.utils import ddf_locations

import rubin_scheduler.scheduler.basis_functions as basis_functions
import rubin_scheduler.scheduler.detailers as detailers
from rubin_scheduler.skybrightness_pre import dark_m5
from rubin_scheduler.site_models import SeeingModel

import schedview.compute as schedview_compute

In [2]:
endpoints_dev = connections.get_clients(tokenfile=os.path.join(os.path.expanduser("~"), ".lsst/usdf_rsp"), site='usdf-dev')
endpoints_dev

endpoints = endpoints_dev

In [3]:
#day_obs = Time(Time.now().mjd - 0.5, format='mjd', scale='tai').iso[0:10]
day_obs = "2026-06-29"

queue = 1


day_obs_time = Time(f"{day_obs}T12:00:00", format='isot', scale='tai')
tnow = Time.now()
observer = Observer.at_site('Rubin')
sunset = Time(observer.sun_set_time(day_obs_time, which='next', horizon=-0*u.deg), format='jd')
sunrise = Time(observer.sun_rise_time(day_obs_time, which='next', horizon=-0*u.deg), format='jd')
print(day_obs, 'sunset', sunset.iso,  'sunrise', sunrise.iso, 'now', Time.now().iso)

topic = "lsst.sal.Scheduler.logevent_target"
#topic = "lsst.sal.Scheduler.logevent_largeFileObjectAvailable"
targets = endpoints['efd'].select_time_series(topic, '*', sunset, sunrise, index=queue)
for c in ['ra', 'decl', 'skyAngle']:
    targets[c] = targets[c].astype(float)
if len(targets) == 0:
    display(endpoints['efd'].select_top_n(topic, '*', 2, index=queue))
print(len(targets))

topic = "lsst.sal.Scheduler.logevent_observation"
observations = endpoints['efd'].select_time_series(topic, '*', sunset, sunrise, index=queue)
for c in ['ra', 'decl', 'rotSkyPos']:
    observations[c] = observations[c].astype(float)
print(len(observations))

topic = "lsst.sal.Scheduler.logevent_largeFileObjectAvailable"
snapshots = endpoints['efd'].select_time_series(topic, '*', sunset, sunrise, index=queue)
print(len(snapshots))

if len(targets) > 0 and len(observations) > 0:
    to = pd.merge_asof(
                targets.sort_values("targetId").reset_index("time"),
                observations.sort_values("targetId").reset_index("time"),
                on="targetId",
                left_by=["ra", "decl", "skyAngle"],
                right_by=["ra", "decl", "rotSkyPos"],
                suffixes=("", "_o"),
                allow_exact_matches=True,
                direction="forward",
            )
    to.sort_values(by="time", inplace=True)
    to = to.astype({"targetId": int, "blockId": int, "skyAngle": float})
    print(len(to))
elif len(targets) > 0:
    to = pd.DataFrame(targets.sort_values("targetId").reset_index("time"))
    to['time_o'] = np.nan
    print("targets only")
else:
    to = None

2026-06-29 sunset 2026-06-29 21:48:43.224 sunrise 2026-06-30 11:44:28.099 now 2026-06-30 20:29:35.993
886
875
891
886

In [4]:
visits = endpoints['consdb'].get_visits("lsstcam", sunset, sunrise)

In [5]:
programs = ["BLOCK-365", "BLOCK-407", "BLOCK-408", "BLOCK-416"]
visits.query("science_program in @programs")[['target_name', 'visit_id', 'obs_start',  'observation_reason', 'science_program', 'band',  'zero_point_1s_pred', 'fwhm_eff', 'clouds']]

,target_name,visit_id,obs_start,observation_reason,science_program,band,zero_point_1s_pred,fwhm_eff,clouds
10,lowdust,2026062900045,2026-06-29T22:51:19.330000,twilight_near_sun,BLOCK-407,r,28.376665,2.027672,0.060814
11,"nes, lowdust",2026062900046,2026-06-29T22:51:47.622000,twilight_near_sun,BLOCK-407,r,28.360304,2.228412,0.082849
12,nes,2026062900047,2026-06-29T22:52:16.287000,twilight_near_sun,BLOCK-407,r,28.342320,2.060431,0.048547
13,lowdust,2026062900048,2026-06-29T22:52:52.253000,twilight_near_sun,BLOCK-407,r,28.350811,1.692259,0.008915
14,lowdust,2026062900049,2026-06-29T22:53:20.510000,twilight_near_sun,BLOCK-407,r,28.340926,1.790782,0.021362
...,...,...,...,...,...,...,...,...,...
880,nes,2026062900915,2026-06-30T10:42:10.439000,twilight_near_sun,BLOCK-407,r,28.361989,1.360721,-0.022051
881,nes,2026062900916,2026-06-30T10:42:39.872000,twilight_near_sun,BLOCK-407,r,28.358934,1.339038,-0.021399
882,nes,2026062900917,2026-06-30T10:43:07.478000,twilight_near_sun,BLOCK-407,r,28.343403,1.360780,-0.013822
883,nes,2026062900918,2026-06-30T10:43:38.636000,twilight_near_sun,BLOCK-407,r,28.354687,1.421419,0.016755
884,nes,2026062900919,2026-06-30T10:44:06.886000,twilight_near_sun,BLOCK-407,r,28.370456,1.362171,0.010639

In [6]:
ack = to.groupby("snapshotUri").first()[['time', 'ra', 'decl', 'skyAngle', 'filter', 'note', 'targetName', 'airmass', 'targetId', 'blockId']]

In [11]:
to["snapshotUri"].iloc[668]

'https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T07:30:07.244.p'

In [74]:
ack.shape

(884, 10)

In [77]:
ack.iloc[845:880]

,time,ra,decl,skyAngle,filter,note,targetName,airmass,targetId,blockId
snapshotUri,,,,,,,,,,
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T09:52:49.772.p,2026-06-30 09:56:32.047814+00:00,9.221615,-43.931937,271.813129,i,"DD:ELAISS1, 3900","ddf_elaiss1, lowdust",1.047691,23554,117886
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T09:52:51.808.p,2026-06-30 09:57:14.305151+00:00,336.541332,-26.042034,338.757095,z,greedy z,lowdust,1.044578,23555,117887
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T09:52:54.253.p,2026-06-30 10:00:15.758250+00:00,333.083581,-25.474442,338.979683,z,greedy z,lowdust,1.069966,23556,117888
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:00:54.663.p,2026-06-30 10:00:58.244665+00:00,21.916662,-48.346489,176.495862,i,greedy i,lowdust,1.103689,23557,117889
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:00:56.871.p,2026-06-30 10:05:10.819130+00:00,15.873041,-43.756655,178.078363,i,greedy i,lowdust,1.060459,23558,117890
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:00:58.925.p,2026-06-30 10:05:55.058958+00:00,23.267661,-45.724636,169.804895,i,greedy i,lowdust,1.107860,23559,117891
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:06:34.873.p,2026-06-30 10:10:08.063366+00:00,340.007763,-26.459993,337.504729,z,greedy z,lowdust,1.047583,23560,117892
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:06:37.396.p,2026-06-30 10:10:52.372235+00:00,341.086956,-29.094480,329.129006,z,greedy z,lowdust,1.043825,23561,117893
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:06:39.726.p,2026-06-30 10:11:39.658224+00:00,338.981077,-23.828555,344.402586,z,greedy z,lowdust,1.057528,23562,117894
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:12:18.670.p,2026-06-30 10:15:55.127849+00:00,26.565649,-47.911567,173.050857,i,greedy i,lowdust,1.122294,23563,117895
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:12:20.986.p,2026-06-30 10:16:39.434337+00:00,20.226740,-43.464848,174.645727,i,greedy i,lowdust,1.060633,23564,117896
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:12:23.148.p,2026-06-30 10:17:33.728010+00:00,25.348568,-50.567158,179.143160,i,greedy i,lowdust,1.133424,23565,117897
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:18:12.657.p,2026-06-30 10:21:46.931924+00:00,343.485337,-26.788174,336.699655,z,greedy z,lowdust,1.048089,23566,117898
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:18:14.926.p,2026-06-30 10:22:32.206711+00:00,342.385619,-24.175183,343.800043,z,greedy z,lowdust,1.058087,23567,117899
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:18:17.118.p,2026-06-30 10:23:22.687969+00:00,344.649712,-29.399100,328.018709,z,greedy z,lowdust,1.036991,23568,117900
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:24:01.627.p,2026-06-30 10:27:26.281810+00:00,62.458772,1.189173,105.676374,r,"twilight_near_sun, 0","nes, lowdust",2.243831,23569,117901
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:24:03.824.p,2026-06-30 10:28:12.635048+00:00,62.051098,4.325009,104.340577,r,"twilight_near_sun, 0",nes,2.359124,23570,117902
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:24:05.781.p,2026-06-30 10:29:03.921683+00:00,61.562734,7.440356,103.063297,r,"twilight_near_sun, 0",nes,2.454325,23571,117903
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:29:42.900.p,2026-06-30 10:33:54.244856+00:00,58.772664,8.783192,101.456337,r,"twilight_near_sun, 0",nes,2.323889,23572,117904
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:29:45.032.p,2026-06-30 10:34:22.522372+00:00,55.241282,13.158651,98.267729,r,"twilight_near_sun, 0",nes,2.421514,23573,117905
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:29:46.970.p,2026-06-30 10:34:51.829850+00:00,54.533477,16.206052,96.921816,r,"twilight_near_sun, 0",nes,2.577674,23574,117906
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:35:30.787.p,2026-06-30 10:35:19.578946+00:00,51.508377,17.424714,94.803790,r,"twilight_near_sun, 0",nes,2.307744,23575,117907
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:35:32.946.p,2026-06-30 10:35:51.875956+00:00,52.289834,14.420172,96.234180,r,"twilight_near_sun, 0",nes,2.167205,23576,117908
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:35:35.155.p,2026-06-30 10:36:20.147495+00:00,55.931286,10.100800,99.678931,r,"twilight_near_sun, 0",nes,2.196119,23577,117909
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:36:59.103.p,2026-06-30 10:36:48.721413+00:00,56.570224,7.011349,101.151621,r,"twilight_near_sun, 0",nes,2.081419,23578,117910
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:37:01.316.p,2026-06-30 10:37:18.981592+00:00,59.331866,5.672969,102.832012,r,"twilight_near_sun, 0",nes,2.101807,23579,117911
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:37:03.484.p,2026-06-30 10:37:49.280958+00:00,57.128951,3.883739,102.685858,r,"twilight_near_sun, 0",nes,1.882014,23580,117912
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:38:28.298.p,2026-06-30 10:38:18.626308+00:00,59.808275,2.533796,104.267041,r,"twilight_near_sun, 0","nes, lowdust",2.010799,23581,117913
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:38:30.265.p,2026-06-30 10:38:49.924548+00:00,62.458772,1.189173,105.676374,r,"twilight_near_sun, 1","nes, lowdust",2.036490,23582,117914
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:38:32.508.p,2026-06-30 10:39:21.193198+00:00,62.051098,4.325009,104.340577,r,"twilight_near_sun, 1",nes,2.131370,23583,117915
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:40:00.217.p,2026-06-30 10:39:51.309999+00:00,61.562734,7.440356,103.063297,r,"twilight_near_sun, 1",nes,2.191500,23584,117916
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:40:02.192.p,2026-06-30 10:40:23.567743+00:00,58.772664,8.783192,101.456337,r,"twilight_near_sun, 1",nes,2.169879,23585,117917
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:40:04.284.p,2026-06-30 10:40:51.833609+00:00,55.241282,13.158651,98.267729,r,"twilight_near_sun, 1",nes,2.263204,23586,117918
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:41:30.832.p,2026-06-30 10:41:21.331045+00:00,54.533477,16.206052,96.921816,r,"twilight_near_sun, 1",nes,2.382436,23587,117919
https://s3.cp.lsst.org/rubinobs-lfa-cp/Scheduler:1/Scheduler:1/2026/06/29/Scheduler:1_Scheduler:1_2026-06-30T10:41:32.938.p,2026-06-30 10:41:51.638449+00:00,51.508377,17.424714,94.803790,r,"twilight_near_sun, 1",nes,2.229324,23588,117920

In [63]:
to[["time", "targetId"]][200:250]

                                time  targetId
868 2026-06-30 01:16:09.185934+00:00     27628
869 2026-06-30 01:17:00.452873+00:00     27629
870 2026-06-30 01:17:44.711662+00:00     27630
871 2026-06-30 01:18:32.607842+00:00     27631
872 2026-06-30 01:19:21.891423+00:00     27632
873 2026-06-30 01:20:08.180900+00:00     27633
874 2026-06-30 01:20:52.823195+00:00     27634
875 2026-06-30 01:21:40.128496+00:00     27635
876 2026-06-30 01:22:25.436586+00:00     27636
877 2026-06-30 01:23:14.056399+00:00     27637
878 2026-06-30 01:24:00.332751+00:00     27638
879 2026-06-30 01:24:50.681695+00:00     27639
880 2026-06-30 01:25:34.703229+00:00     27640
881 2026-06-30 01:26:23.008179+00:00     27641
882 2026-06-30 01:27:07.253556+00:00     27642
883 2026-06-30 01:27:53.648947+00:00     27643
884 2026-06-30 01:28:38.128502+00:00     27644
885 2026-06-30 01:29:38.402876+00:00     27645
3   2026-06-30 01:32:30.310298+00:00     22927
4   2026-06-30 01:32:31.513747+00:00     22928
5   2026-06-30 01:32:32.628694+00:00     22929
6   2026-06-30 01:33:59.293156+00:00     22930
7   2026-06-30 01:34:43.633295+00:00     22931
8   2026-06-30 01:35:30.942961+00:00     22932
9   2026-06-30 01:36:17.094235+00:00     22933
10  2026-06-30 01:37:02.394417+00:00     22934
11  2026-06-30 01:37:45.728659+00:00     22935
12  2026-06-30 01:38:32.702105+00:00     22936
13  2026-06-30 01:39:20.985877+00:00     22937
14  2026-06-30 01:40:07.341312+00:00     22938
15  2026-06-30 01:40:51.005986+00:00     22939
16  2026-06-30 01:41:38.358262+00:00     22940
17  2026-06-30 01:42:22.634244+00:00     22941
18  2026-06-30 01:43:13.634434+00:00     22942
19  2026-06-30 01:43:57.041558+00:00     22943
20  2026-06-30 01:44:42.381645+00:00     22944
21  2026-06-30 01:45:27.320325+00:00     22945
22  2026-06-30 01:46:26.604684+00:00     22946
23  2026-06-30 01:47:08.917717+00:00     22947
24  2026-06-30 01:47:58.420567+00:00     22948
25  2026-06-30 01:48:41.703108+00:00     22949
26  2026-06-30 01:49:28.985466+00:00     22950
27  2026-06-30 01:50:10.976524+00:00     22951
28  2026-06-30 01:51:09.243893+00:00     22952
29  2026-06-30 01:51:53.542653+00:00     22953
30  2026-06-30 01:52:38.222609+00:00     22954
31  2026-06-30 01:53:23.506231+00:00     22955
32  2026-06-30 01:54:09.774630+00:00     22956
33  2026-06-30 01:54:53.974038+00:00     22957
34  2026-06-30 01:55:42.282165+00:00     22958

In [73]:
visits.iloc[849:900][['obs_start', 'visit_id',  'band',  "scheduler_note"]]

                      obs_start       visit_id band        scheduler_note
849  2026-06-30T10:01:02.690000  2026062900884    i      DD:ELAISS1, 3900
850  2026-06-30T10:05:15.436000  2026062900885    z              greedy z
851  2026-06-30T10:05:59.253000  2026062900886    z              greedy z
852  2026-06-30T10:10:12.343000  2026062900887    i              greedy i
853  2026-06-30T10:10:56.449000  2026062900888    i              greedy i
854  2026-06-30T10:11:43.583000  2026062900889    i              greedy i
855  2026-06-30T10:15:58.977000  2026062900890    z              greedy z
856  2026-06-30T10:16:43.944000  2026062900891    z              greedy z
857  2026-06-30T10:17:38.290000  2026062900892    z              greedy z
858  2026-06-30T10:21:51.497000  2026062900893    i              greedy i
859  2026-06-30T10:22:36.510000  2026062900894    i              greedy i
860  2026-06-30T10:23:26.289000  2026062900895    i              greedy i
861  2026-06-30T10:27:30.737000  2026062900896    z              greedy z
862  2026-06-30T10:28:16.266000  2026062900897    z              greedy z
863  2026-06-30T10:29:07.942000  2026062900898    z              greedy z
864  2026-06-30T10:34:13.417000  2026062900899    r  twilight_near_sun, 0
865  2026-06-30T10:34:41.477000  2026062900900    r  twilight_near_sun, 0
866  2026-06-30T10:35:10.680000  2026062900901    r  twilight_near_sun, 0
867  2026-06-30T10:35:38.113000  2026062900902    r  twilight_near_sun, 0
868  2026-06-30T10:36:11.295000  2026062900903    r  twilight_near_sun, 0
869  2026-06-30T10:36:39.431000  2026062900904    r  twilight_near_sun, 0
870  2026-06-30T10:37:07.295000  2026062900905    r  twilight_near_sun, 0
871  2026-06-30T10:37:38.188000  2026062900906    r  twilight_near_sun, 0
872  2026-06-30T10:38:08.565000  2026062900907    r  twilight_near_sun, 0
873  2026-06-30T10:38:36.928000  2026062900908    r  twilight_near_sun, 0
874  2026-06-30T10:39:09.387000  2026062900909    r  twilight_near_sun, 0
875  2026-06-30T10:39:40.533000  2026062900910    r  twilight_near_sun, 0
876  2026-06-30T10:40:08.070000  2026062900911    r  twilight_near_sun, 0
877  2026-06-30T10:40:42.523000  2026062900912    r  twilight_near_sun, 1
878  2026-06-30T10:41:10.552000  2026062900913    r  twilight_near_sun, 1
879  2026-06-30T10:41:38.766000  2026062900914    r  twilight_near_sun, 1
880  2026-06-30T10:42:10.439000  2026062900915    r  twilight_near_sun, 1
881  2026-06-30T10:42:39.872000  2026062900916    r  twilight_near_sun, 1
882  2026-06-30T10:43:07.478000  2026062900917    r  twilight_near_sun, 1
883  2026-06-30T10:43:38.636000  2026062900918    r  twilight_near_sun, 1
884  2026-06-30T10:44:06.886000  2026062900919    r  twilight_near_sun, 1
885  2026-06-30T11:00:05.361000  2026062900920    i
886  2026-06-30T11:00:35.878000  2026062900921    i
887  2026-06-30T11:01:06.369000  2026062900922    i
888  2026-06-30T11:26:48.484000  2026062900923    i
889  2026-06-30T11:27:18.974000  2026062900924    i
890  2026-06-30T11:27:49.292000  2026062900925    i
891  2026-06-30T11:28:19.594000  2026062900926    i
892  2026-06-30T11:31:20.579000  2026062900927    i
893  2026-06-30T11:31:53.834000  2026062900928    i
894  2026-06-30T11:32:27.267000  2026062900929    i
895  2026-06-30T11:33:00.537000  2026062900930    i
896  2026-06-30T11:34:21.660000  2026062900931    i
897  2026-06-30T11:34:52.058000  2026062900932    i
898  2026-06-30T11:35:22.378000  2026062900933    i
899  2026-06-30T11:35:52.709000  2026062900934    i

In [26]:
to.columns

Index(['time', 'airmass', 'alt', 'az', 'blockId', 'cloud', 'decl',
       'exposureTimes0', 'exposureTimes1', 'exposureTimes2', 'exposureTimes3',
       'exposureTimes4', 'exposureTimes5', 'exposureTimes6', 'exposureTimes7',
       'exposureTimes8', 'exposureTimes9', 'filter', 'isSequence', 'moonAlt',
       'moonAz', 'moonDec', 'moonDistance', 'moonPhase', 'moonRa', 'note',
       'numExposures', 'numProposals', 'offsetX', 'offsetY',
       'private_efdStamp', 'private_identity', 'private_kafkaStamp',
       'private_origin', 'private_rcvStamp', 'private_revCode',
       'private_seqNum', 'private_sndStamp', 'proposalId0', 'proposalId1',
       'proposalId2', 'proposalId3', 'proposalId4', 'ra', 'requestMjd',
       'requestTime', 'rotAngle', 'salIndex', 'schedulerNote', 'seeing',
       'sequenceDuration', 'sequenceNVisits', 'sequenceVisits', 'skyAngle',
       'skyBrightness', 'slewTime', 'snapshotUri', 'solarElong', 'sunAlt',
       'sunAz', 'sunDec', 'sunRa', 'targetId', 'targetName', 'time_o',
       'additionalInformation', 'blockId_o', 'exptime', 'filter_o', 'mjd',
       'nexp', 'private_efdStamp_o', 'private_identity_o',
       'private_kafkaStamp_o', 'private_origin_o', 'private_rcvStamp_o',
       'private_revCode_o', 'private_seqNum_o', 'private_sndStamp_o',
       'rotSkyPos', 'salIndex_o'],
      dtype='str')

In [68]:
visits.shape

(917, 250)